<h1 class="text-center text-warning"><?php echo $this->locale->_('role_title');?></h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form(['','class'=>'text-start']);
echo '<label for="name" class="form-label">Role Name</label>';
echo $this->tag->textField(["name", 'class'=>"form-control"]);
echo $this->tag->submitButton([$this->locale->_('role_title'), 'class'=>"btn btn-primary mt-3"]);
?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
