<h1 class="text-center text-warning">Login</h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form(['','class'=>'text-start']);

echo '<label for="email" class="form-label">Email</label>';
echo $this->tag->textField(["email", 'class'=>"form-control"]);

echo '<label for="password" class="form-label">Password</label>';
echo $this->tag->passwordField(["password", 'class'=>"form-control"]);
echo $this->tag->submitButton(['Login', 'class'=>"btn btn-primary mt-3"]);
?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
<div class="alert alert-success w-50 m-auto mt-2 text-break"><?php if (isset($token)) echo($token); ?></div>
