<h1 class="text-center text-warning"><?php echo $this->locale->_('product_title');?></h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form(['','class'=>'text-start']);
echo '<label for="name" class="form-label">Product Name</label>';
echo $this->tag->textField(["name", 'class'=>"form-control", 'value'=>$product->name ?? '']);

echo '<label for="description" class="form-label">Product Description</label>';
echo $this->tag->textArea(["description", 'class'=>"form-control", 'value'=>$product->description ?? '']);

echo '<label for="tags" class="form-label">Product tags</label>';
echo $this->tag->textField(["tags", 'class'=>"form-control", 'value'=>$product->tags ?? '']);

echo '<label for="price" class="form-label">Product price</label>';
echo $this->tag->textField(["price", 'class'=>"form-control", 'value'=>$product->price ?? '']);

echo '<label for="stock" class="form-label">Product Stock</label>';
echo $this->tag->textField(["stock", 'class'=>"form-control", 'value'=>$product->stock ?? '']);
if (!isset($product)) {
    echo $this->tag->submitButton(['Add Product', 'class'=>"btn btn-primary mt-3"]);
} else {
    echo $this->tag->submitButton(['Update Product', 'class'=>"btn btn-primary mt-3"]);
}
?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
