<h1 class="text-center text-warning"><?php echo $this->locale->_('signup_title');?></h1>
<div class="w-50 m-auto">
<?php

echo $this->tag->form(['','class'=>'text-start']);

echo '<label for="name" class="form-label">Name</label>';
echo $this->tag->textField(["name", 'class'=>"form-control", 'value'=>$user->name ?? '']);

echo '<label for="email" class="form-label">Email</label>';
echo $this->tag->textField(["email", 'class'=>"form-control", 'value'=>$user->email ?? '']);

echo '<label for="password" class="form-label">Password</label>';
echo $this->tag->passwordField(["password", 'class'=>"form-control", 'value'=>$user->password ?? '']);
?>
<label for="role" class="form-label">Select Role</label>
<select class="form-select" name="role" aria-label="Default select example">
  <option value="" selected></option>
    <?php
        foreach ($roles as $role) {
            if (isset($user) && $user->role==$role->id) {
                echo '<option value="'.$role->id.'" selected>'.$role->name.'</option>';
            } else {
                echo '<option value="'.$role->id.'">'.$role->name.'</option>';
            }
        }
    ?>
  
</select>
<?php
if (!isset($user)) {
    echo $this->tag->submitButton([$this->locale->_('signup_title'), 'class'=>"btn btn-primary mt-3"]);
} else {
    echo $this->tag->submitButton(['Update User', 'class'=>"btn btn-primary mt-3"]);;
}
?>
</div>
<div class="alert alert-danger w-50 m-auto mt-2"><?php if (isset($message)) echo $message; ?></div>
<div class="alert alert-success w-50 m-auto mt-2 text-break">Token:<br><?php if (isset($token)) echo $token; ?></div>
