<div class="container">
    <table class="table table-hover">
        <thead class="text-light bg-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
            <?php
            foreach ($users as $user) {
                echo '<tr>
                        <th scope="row">'.$user->id.'</th>
                        <td>'.$user->name.'</td>
                        <td>'.$user->email.'</td>
                        <td>'.$user->role.'</td>
                        <td><a href=user/add?id='.$user->id.'>edit</a></td>
                    </tr>';
            }
            ?>
        </tbody>

    </table>
</div>